### ISSUE TITLE
How to make prod and dev version?

### ISSUE THREAD

**Issue by VisualMafia** [centrual/cordova-template-framework7-vue-webpack#137]
Interested in minification. Thanks

**Comment by lgally** [comment]
Hi, I have found a bit of a crappy workaround... in webpack.config.js make the following changes;

    mode: "production",
    //mode: (env && typeof env.release !== 'undefined' && env.release) ? "production" : "development",

**Comment by caiobiodere** [comment]
hey @VisualMafia and @gally90 I created three different files for each one of these configurations:

webpack.config.dev.js
webpack.config.release.js
webpack.config.server.js

if you wanna use the minification with cordova in order to create a new build just follow this command:
cordova run (ios | android) --release

Check the last release: [Release - 2.3.0](https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/releases/tag/2.3.0)
