### ISSUE TITLE
Phonegap build tip

### ISSUE THREAD

**Issue by innoflash** [centrual/cordova-template-framework7-vue-webpack#139]
Hey fellas, i usually have issues developing my app using windows with Android Studio so i have opted to Phonegap Build. 

I used to win when using Framework7 with just Phonegap but now i want this one with VueJS but i cant seem to get the best way to go about it, current i have a repo 
[https://github.com/innoflash/hw2](https://github.com/innoflash/hw2) 
that i am importing to phonegap build.

The apk is built but when i run it i get the following error
![screenshot_20181230-012519](https://user-images.githubusercontent.com/12772919/50543037-17fd6c00-0bd3-11e9-9c05-50c12ac96615.png)

How best can i deal with this in phonegap build

**Comment by caiobiodere** [comment]
did you check the readme file? I wrote something because of some phonegap problems, I would like you to try using cordova following this guide:

[Cordova](https://cordova.apache.org/docs/en/latest/guide/cli/)

IMPORTANT: Phonegap build tools not supported currently. I suggest to use cordova with this template.

**Comment by caiobiodere** [comment]
I'm closing but please let me know if you need any other help
