### ISSUE TITLE
White screen (Linux OS)

### ISSUE THREAD

**Issue by insign** [centrual/cordova-template-framework7-vue-webpack#4]
Sorry If I skipped any step but, running `cordova run browser -- --live-reload` show the right title, but the page is completely white. Is it right?

Great project, thanks.

**Comment by insign** [comment]
![image](https://cloud.githubusercontent.com/assets/1113045/22525729/3cd22706-e8a7-11e6-95cb-c9e9aaf91832.png)

I'll try to downgrade npm...

**Comment by insign** [comment]
If downgrade to 4.x I get the error again (the error that I solved upgrading the node):

`Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

**Comment by centrual** [comment]
Hello @insign 

First problem about node-sass dependency. They updated library 2 days ago. You can check from https://github.com/sass/node-sass/releases . You need to redownload node-sass for fix. I haven't linux environment currently, i'll update the template soon, so i'll test everything in mac os too.

Second problem about ES6. Template's minimum requirement is node version 6.5.0 because of ES6 features. but, you can transpile beforedep.js and hookers.js to ES5 with [babel](https://babeljs.io/repl/) if you want.

If you have time, please wait 1 week for update. I'll check every problem.

Have a great day!

**Comment by insign** [comment]
Ok, I can be a tester of Linux if you need.

**Comment by centrual** [comment]
@insign It can be great!

**Comment by insign** [comment]
Please, verify ASAP, this project is amazing.

**Comment by centrual** [comment]
@insign I started to make new version. Keep in touch. ~You can track https://github.com/centrual/cordova-template-framework7-vue-webpack/projects/1.~

I updated the template. Can you read instructions and check one more time?

Thank you so much.
Have a great day!

**Comment by insign** [comment]
I really thank you, but for now, I'm trying Quasar Framework.

**Comment by centrual** [comment]
Okay, thank you too @insign. Closing the issue.

Have a great day!
