### ISSUE TITLE
iOS simulator with live reload disconnect 

### ISSUE THREAD

**Issue by asifkilwani** [centrual/cordova-template-framework7-vue-webpack#44]
I am running cordova emulate ios -- --lr, Simulator loads fine but any changes in the code it disconnect from Simulator with error [WDS] Disconnected!

I am playing with Cordova plugin and right now it's difficult to re-run the command to test every line of code.

is there any fix for that?

**Comment by centrual** [comment]
please read the docs.

**Comment by centrual** [comment]
# WARNING (For Linux and Mac OS users):

For live-reload i can't find easy way to do fixed version of this. But you can develop your app with this way:

cordova platform add ios browser (browser needs for development in live-reload mode.)
`cordova run ios -- --lr` (wait till app opens in your ios emulator or phone. it will close console output after publish, so live-reload will not work. don't close the app and go to next step.)
`cordova run browser -- --lr` (you can use live-reload in your phone-emulator and browser at same time. you can edit your files in live-reload mode now.)

**Comment by yipcma** [comment]
@centrual  I was running as instructed and got this: 
```
cordova run browser -- --lr
Before deploy hook started...
Checking is node modules installed...
Node modules already installed.
Watcher ready!
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8081
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

**Comment by centrual** [comment]
hello, i'm on phone so i give short answer:

1. Close all node.js programs from task manager
2. It's not related with port but it's good to check: close all java programs from task manager.
3. check 8081 port. If not free, search all '8081' texts in your project files and change all '8081' ports to another port number. It's not hard. probably you need to change 2 files.

if you can't fix, i'll write detailed instruction for that in 2 days.

**Comment by yipcma** [comment]
hi, nth's on port 8081, awaits further instructions. PS: am on macOS

**Comment by Robula** [comment]
@centrual I'm experiencing the same issue as @yipcma, I cannot get live reload happening on iOS simulator without port in use error. Looks like running `cordova run ios -- --lr` opens 8081 despite terminal returning causing `cordova run browser -- --lr` to fail.

Any work arounds please? Thanks.

**Comment by antontsvil** [comment]
I'm having this same issue on mac. After starting the ios server, it runs on port 8081. So running the browser on port 8081 returns the error @yipcma got. The browser can't run because the ios one is already using the port. Here's an overview of what I've attempted :

`cordova run ios -- --lr` _runs fine, ios emulator opens and runs the app_
`cordova run browser -- --lr` _EADDRINUSE error like others have gotten_
At this point I assume I have to end the ios server to allow the browser to run
`lsof -i :8081`_to identify what's running on port 8081_
`kill -9 <PID>`_to kill the original ios process so 8081 is now open_
`cordova run browser -- --lr`_runs fine on browser, still no live reload_

I'm confused by the recommended workaround in the documentation. How are we meant to run two different local servers on the same port? How is running both of them at the same time on the same port (not possible) meant to fix live reloading? Also changing the port in the local files will still cause both commands to use the same new port, wouldn't it? Please advise @centrual, thank you!

Edit : using the phonegap command in place of the cordova command seemed to make live reload work somehow.

**Comment by yelban** [comment]
seems to `cordova run ios -- --lr` exit and not release port 8081 correctly
my workaround is do `killall -9 node` 
then `cordova run browser -- --lr` will work

**Comment by yelban** [comment]
`cordova run ios -- --lr` can not assign device/emulator target
so it need to unplug all ios devies, then you can start a ios emulator by use
`cordova run ios -- --lr` 

then do port cleaning by use
`killall -9 node`

then you can do any `cordova emulate android -- --lr`, `cordova run android -- --lr`, ...
( just do not run `cordova emulate ios --target=iPhone-X --lr`, this couldn't hot reload )

if any `throw er; // Unhandled 'error' event`, just do `killall -9 node` again.
