### ISSUE TITLE
Error : $export is not a function

### ISSUE THREAD

**Issue by anuragnagarkota** [centrual/cordova-template-framework7-vue-webpack#95]
Hey

First of thanks for this wonderful work. I have just install it and installation was fine, but when I ran the command cordova run android -- --lr it throws the following error-

TypeError: $export is not a function
  
  - es6.object.define-property.js?:5 eval
    [.]/[core-js]/library/modules/es6.object.define-property.js?:5:1

Thanks

**Comment by hamdallah90** [comment]
Just remove line 46 in file webpack.config.js

this is the line
{test: /\.js$/, exclude: /node_modules\/(?!(framework7|framework7-vue|template7|dom7)\/).*/, use: {loader: 'babel-loader', options: {presets: ['env'], plugins: [ 'transform-runtime', 'transform-object-rest-spread' ]}}}
      

just remove it

**Comment by sank3** [comment]
@hamdallah90 thanks it worked for me

**Comment by caiobiodere** [comment]
Hey guys I don't know if removing line 46 is a good idea because we are using babel for android api 23.

Could you guys check your npm, node and cordova versions before running the application?

Npm version: 5.6.0
Node version: 8.9.4
Cordova version: 8.0.0
cordova-android version: 7.0.0

<img width="1679" alt="screen shot 2018-03-06 at 12 20 27 pm" src="https://user-images.githubusercontent.com/1935649/37041012-e7981008-2139-11e8-8fcb-203d104b3e8c.png">

**Comment by qppq54s** [comment]
@caiobiodere @anuragnagarkota @hamdallah90 @sank3 
In Windows, modulePath would be \project-name\node_modules\MY_MODULE
In Mac, modulePath would be /project-name/node_modules/MY_MODULE
change line 46 from
```
{test: /\.js$/, exclude: /node_modules\/(?!(framework7|framework7-vue|template7|dom7)\/).*/, use: {loader: 'babel-loader', options: {presets: ['env'], plugins: [ 'transform-runtime', 'transform-object-rest-spread' ]}}}
```
to
```
 {test: /\.js$/, exclude: /node_modules(\/|\\)(?!(framework7|framework7-vue|template7|dom7)(\/|\\)).*/, use: {loader: 'babel-loader', options: {presets: ['env'], plugins: [ 'transform-runtime', 'transform-object-rest-spread' ]}}}
```
problem solved!

**Comment by caiobiodere** [comment]
I made your tip :) thank you so much @qppq54s
